// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrdLvU3tDYI8xAKA17jWQn_pUOXLAA5To',
    appId: '1:261817200187:web:7204570cd972c31152761e',
    messagingSenderId: '261817200187',
    projectId: 'ecommerce-a2dee',
    authDomain: 'ecommerce-a2dee.firebaseapp.com',
    storageBucket: 'ecommerce-a2dee.appspot.com',
    measurementId: 'G-2GTWXYWE1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkwgpTtzYBfVZetXz-cyGPjjhsmWzRNvo',
    appId: '1:261817200187:android:56aa64e009d342bb52761e',
    messagingSenderId: '261817200187',
    projectId: 'ecommerce-a2dee',
    storageBucket: 'ecommerce-a2dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgp8jPf7NMXd55ecuDyfHahxwFW_5p8TA',
    appId: '1:261817200187:ios:eab82cc95f93994752761e',
    messagingSenderId: '261817200187',
    projectId: 'ecommerce-a2dee',
    storageBucket: 'ecommerce-a2dee.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgp8jPf7NMXd55ecuDyfHahxwFW_5p8TA',
    appId: '1:261817200187:ios:eab82cc95f93994752761e',
    messagingSenderId: '261817200187',
    projectId: 'ecommerce-a2dee',
    storageBucket: 'ecommerce-a2dee.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrdLvU3tDYI8xAKA17jWQn_pUOXLAA5To',
    appId: '1:261817200187:web:c28e883c6531920252761e',
    messagingSenderId: '261817200187',
    projectId: 'ecommerce-a2dee',
    authDomain: 'ecommerce-a2dee.firebaseapp.com',
    storageBucket: 'ecommerce-a2dee.appspot.com',
    measurementId: 'G-SRWD54FM6R',
  );
}
